# permissions for end users to edit helloapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloapp-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - helloapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - helloapps/status
  verbs:
  - get
